
    // auto generated by gen:icon at package.json
    import React, { lazy } from "react";
    export interface IconProps {
    className?: string;
}
export type iconKeys = "Default" | "ArrowDown" | "ArrowLeft" | "ArrowRight" | "ArrowUp" | "ClipboardOutline1" | "Close" | "Discord" | "Download" | "First" | "Gear" | "Github" | "Lock" | "Logo" | "Minus" | "NoQueue" | "NoCoin" | "OpenSource" | "Pause" | "People" | "Play" | "Plus" | "Second" | "Signal" | "Speedometer" | "Start" | "Stop" | "TextCursor" | "Third" | "Verified" | "Youtube";

 const Default = lazy(async () => await import("./icons/Default"))
const ArrowDown = lazy(async () => await import("./icons/ArrowDown"))
const ArrowLeft = lazy(async () => await import("./icons/ArrowLeft"))
const ArrowRight = lazy(async () => await import("./icons/ArrowRight"))
const ArrowUp = lazy(async () => await import("./icons/ArrowUp"))
const ClipboardOutline1 = lazy(async () => await import("./icons/ClipboardOutline1"))
const Close = lazy(async () => await import("./icons/Close"))
const Discord = lazy(async () => await import("./icons/Discord"))
const Download = lazy(async () => await import("./icons/Download"))
const First = lazy(async () => await import("./icons/First"))
const Gear = lazy(async () => await import("./icons/Gear"))
const Github = lazy(async () => await import("./icons/Github"))
const Lock = lazy(async () => await import("./icons/Lock"))
const Logo = lazy(async () => await import("./icons/Logo"))
const Minus = lazy(async () => await import("./icons/Minus"))
const NoQueue = lazy(async () => await import("./icons/NoQueue"))
const NoCoin = lazy(async () => await import("./icons/NoCoin"))
const OpenSource = lazy(async () => await import("./icons/OpenSource"))
const Pause = lazy(async () => await import("./icons/Pause"))
const People = lazy(async () => await import("./icons/People"))
const Play = lazy(async () => await import("./icons/Play"))
const Plus = lazy(async () => await import("./icons/Plus"))
const Second = lazy(async () => await import("./icons/Second"))
const Signal = lazy(async () => await import("./icons/Signal"))
const Speedometer = lazy(async () => await import("./icons/Speedometer"))
const Start = lazy(async () => await import("./icons/Start"))
const Stop = lazy(async () => await import("./icons/Stop"))
const TextCursor = lazy(async () => await import("./icons/TextCursor"))
const Third = lazy(async () => await import("./icons/Third"))
const Verified = lazy(async () => await import("./icons/Verified"))
const Youtube = lazy(async () => await import("./icons/Youtube"))

 const Icon: Record<iconKeys, React.FC<IconProps>> = {Default : ({className}) => <Default className={className} />,
ArrowDown : ({className}) => <ArrowDown className={className} />,
ArrowLeft : ({className}) => <ArrowLeft className={className} />,
ArrowRight : ({className}) => <ArrowRight className={className} />,
ArrowUp : ({className}) => <ArrowUp className={className} />,
ClipboardOutline1 : ({className}) => <ClipboardOutline1 className={className} />,
Close : ({className}) => <Close className={className} />,
Discord : ({className}) => <Discord className={className} />,
Download : ({className}) => <Download className={className} />,
First : ({className}) => <First className={className} />,
Gear : ({className}) => <Gear className={className} />,
Github : ({className}) => <Github className={className} />,
Lock : ({className}) => <Lock className={className} />,
Logo : ({className}) => <Logo className={className} />,
Minus : ({className}) => <Minus className={className} />,
NoQueue : ({className}) => <NoQueue className={className} />,
NoCoin : ({className}) => <NoCoin className={className} />,
OpenSource : ({className}) => <OpenSource className={className} />,
Pause : ({className}) => <Pause className={className} />,
People : ({className}) => <People className={className} />,
Play : ({className}) => <Play className={className} />,
Plus : ({className}) => <Plus className={className} />,
Second : ({className}) => <Second className={className} />,
Signal : ({className}) => <Signal className={className} />,
Speedometer : ({className}) => <Speedometer className={className} />,
Start : ({className}) => <Start className={className} />,
Stop : ({className}) => <Stop className={className} />,
TextCursor : ({className}) => <TextCursor className={className} />,
Third : ({className}) => <Third className={className} />,
Verified : ({className}) => <Verified className={className} />,
Youtube : ({className}) => <Youtube className={className} />,
} 
 export default Icon;